### ISSUE TITLE
Error on executing lein run

### ISSUE THREAD

**Issue by rcanepa** [yogthos/swagger-service#1]
Hi Dmitri!.

I was trying to follow your duct + compojure-api tutorial but I got stuck at the beginning.

First, I executed the lein new duct swagger-service +example command:

```
[rcanepa@Renzos-MacBook-Pro:clojure_sandbox (master)] λ lein new duct swagger-service +example
Generating a new Duct project named swagger-service...
Run 'lein setup' in the project directory to create local config files.
```

Then, I executed without problems the lein setup:

```
[rcanepa@Renzos-MacBook-Pro:clojure_sandbox (master)] λ cd swagger-service/
[rcanepa@Renzos-MacBook-Pro:swagger-service (master)] λ lein setup
Creating file dev/local.clj
Creating file profiles.clj
```

However, the lein run command threw an java.io.FileNotFoundException:

```
[rcanepa@Renzos-MacBook-Pro:swagger-service (master)] λ lein run
Retrieving com/stuartsierra/component/0.3.0/component-0.3.0.pom from clojars
Retrieving com/stuartsierra/dependency/0.2.0/dependency-0.2.0.pom from clojars
Retrieving duct/duct/0.5.5/duct-0.5.5.pom from clojars
Retrieving meta-merge/meta-merge/0.1.1/meta-merge-0.1.1.pom from clojars
Retrieving ring/ring/1.4.0/ring-1.4.0.pom from clojars
Retrieving ring/ring-devel/1.4.0/ring-devel-1.4.0.pom from clojars
Retrieving clj-stacktrace/clj-stacktrace/0.2.8/clj-stacktrace-0.2.8.pom from clojars
Retrieving ring/ring-defaults/0.1.5/ring-defaults-0.1.5.pom from clojars
Retrieving ring/ring-ssl/0.2.1/ring-ssl-0.2.1.pom from clojars
Retrieving ring/ring-core/1.3.0-RC1/ring-core-1.3.0-RC1.pom from clojars
Retrieving ring/ring-headers/0.1.3/ring-headers-0.1.3.pom from clojars
Retrieving ring/ring-anti-forgery/1.0.0/ring-anti-forgery-1.0.0.pom from clojars
Retrieving ring-jetty-component/ring-jetty-component/0.3.0/ring-jetty-component-0.3.0.pom from clojars
Retrieving com/stuartsierra/component/0.2.3/component-0.2.3.pom from clojars
Retrieving com/stuartsierra/dependency/0.1.1/dependency-0.1.1.pom from clojars
Retrieving suspendable/suspendable/0.1.0/suspendable-0.1.0.pom from clojars
Retrieving reloaded/repl/reloaded.repl/0.2.1/reloaded.repl-0.2.1.pom from clojars
Retrieving eftest/eftest/0.1.0/eftest-0.1.0.pom from clojars
Retrieving progrock/progrock/0.1.1/progrock-0.1.1.pom from clojars
Retrieving mvxcvi/puget/0.8.1/puget-0.8.1.pom from clojars
Retrieving fipp/fipp/0.5.2/fipp-0.5.2.pom from clojars
Retrieving org/clojure/data.finger-tree/0.0.2/data.finger-tree-0.0.2.pom from central
Retrieving transduce/transduce/0.1.0/transduce-0.1.0.pom from clojars
Retrieving kerodon/kerodon/0.7.0/kerodon-0.7.0.pom from clojars
Retrieving peridot/peridot/0.4.0/peridot-0.4.0.pom from clojars
Retrieving ring-mock/ring-mock/0.1.5/ring-mock-0.1.5.pom from clojars
Retrieving org/apache/httpcomponents/httpmime/4.1.3/httpmime-4.1.3.pom from central
Retrieving org/apache/httpcomponents/httpcomponents-client/4.1.3/httpcomponents-client-4.1.3.pom from central
Retrieving org/apache/httpcomponents/project/5/project-5.pom from central
Retrieving org/apache/httpcomponents/httpcore/4.1.4/httpcore-4.1.4.pom from central
Retrieving org/apache/httpcomponents/httpcomponents-core/4.1.4/httpcomponents-core-4.1.4.pom from central
Retrieving enlive/enlive/1.1.6/enlive-1.1.6.pom from clojars
Retrieving org/ccil/cowan/tagsoup/tagsoup/1.2.1/tagsoup-1.2.1.pom from central
Retrieving org/jsoup/jsoup/1.7.2/jsoup-1.7.2.pom from central
Retrieving org/flatland/ordered/1.5.3/ordered-1.5.3.pom from clojars
Retrieving org/flatland/useful/0.9.0/useful-0.9.0.pom from clojars
Retrieving org/clojure/tools.macro/0.1.1/tools.macro-0.1.1.pom from central
Retrieving org/clojure/data.finger-tree/0.0.2/data.finger-tree-0.0.2.jar from central
Retrieving org/apache/httpcomponents/httpcore/4.1.4/httpcore-4.1.4.jar from central
Retrieving org/jsoup/jsoup/1.7.2/jsoup-1.7.2.jar from central
Retrieving org/ccil/cowan/tagsoup/tagsoup/1.2.1/tagsoup-1.2.1.jar from central
Retrieving org/apache/httpcomponents/httpmime/4.1.3/httpmime-4.1.3.jar from central
Retrieving com/stuartsierra/dependency/0.2.0/dependency-0.2.0.jar from clojars
Retrieving meta-merge/meta-merge/0.1.1/meta-merge-0.1.1.jar from clojars
Retrieving duct/duct/0.5.5/duct-0.5.5.jar from clojars
Retrieving ring/ring/1.4.0/ring-1.4.0.jar from clojars
Retrieving ring/ring-devel/1.4.0/ring-devel-1.4.0.jar from clojars
Retrieving com/stuartsierra/component/0.3.0/component-0.3.0.jar from clojars
Retrieving ring/ring-ssl/0.2.1/ring-ssl-0.2.1.jar from clojars
Retrieving clj-stacktrace/clj-stacktrace/0.2.8/clj-stacktrace-0.2.8.jar from clojars
Retrieving ring/ring-headers/0.1.3/ring-headers-0.1.3.jar from clojars
Retrieving ring/ring-anti-forgery/1.0.0/ring-anti-forgery-1.0.0.jar from clojars
Retrieving ring-jetty-component/ring-jetty-component/0.3.0/ring-jetty-component-0.3.0.jar from clojars
Retrieving suspendable/suspendable/0.1.0/suspendable-0.1.0.jar from clojars
Retrieving reloaded/repl/reloaded.repl/0.2.1/reloaded.repl-0.2.1.jar from clojars
Retrieving eftest/eftest/0.1.0/eftest-0.1.0.jar from clojars
Retrieving fipp/fipp/0.5.2/fipp-0.5.2.jar from clojars
Retrieving ring/ring-defaults/0.1.5/ring-defaults-0.1.5.jar from clojars
Retrieving mvxcvi/puget/0.8.1/puget-0.8.1.jar from clojars
Retrieving transduce/transduce/0.1.0/transduce-0.1.0.jar from clojars
Retrieving peridot/peridot/0.4.0/peridot-0.4.0.jar from clojars
Retrieving kerodon/kerodon/0.7.0/kerodon-0.7.0.jar from clojars
Retrieving ring-mock/ring-mock/0.1.5/ring-mock-0.1.5.jar from clojars
Retrieving enlive/enlive/1.1.6/enlive-1.1.6.jar from clojars
Retrieving org/flatland/ordered/1.5.3/ordered-1.5.3.jar from clojars
Retrieving progrock/progrock/0.1.1/progrock-0.1.1.jar from clojars
Retrieving org/flatland/useful/0.9.0/useful-0.9.0.jar from clojars
2015-12-02 08:41:57.725:INFO::main: Logging initialized @3595ms
Exception in thread "main" java.io.FileNotFoundException: Could not locate puget/dispatch__init.class or puget/dispatch.clj on classpath., compiling:(whidbey/repl.clj:1:1)
    at clojure.lang.Compiler.load(Compiler.java:7239)
    at clojure.lang.RT.loadResourceScript(RT.java:371)
    at clojure.lang.RT.loadResourceScript(RT.java:362)
    at clojure.lang.RT.load(RT.java:446)
    at clojure.lang.RT.load(RT.java:412)
    at clojure.core$load$fn__5448.invoke(core.clj:5866)
    at clojure.core$load.doInvoke(core.clj:5865)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5671)
    at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
    at clojure.core$load_lib.doInvoke(core.clj:5710)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:632)
    at clojure.core$load_libs.doInvoke(core.clj:5749)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:632)
    at clojure.core$require.doInvoke(core.clj:5832)
    at clojure.lang.RestFn.invoke(RestFn.java:482)
    at ultra.colorscheme$eval8167$loading__5340__auto____8168.invoke(colorscheme.clj:1)
    at ultra.colorscheme$eval8167.invoke(colorscheme.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6782)
    at clojure.lang.Compiler.eval(Compiler.java:6771)
    at clojure.lang.Compiler.load(Compiler.java:7227)
    at clojure.lang.RT.loadResourceScript(RT.java:371)
    at clojure.lang.RT.loadResourceScript(RT.java:362)
    at clojure.lang.RT.load(RT.java:446)
    at clojure.lang.RT.load(RT.java:412)
    at clojure.core$load$fn__5448.invoke(core.clj:5866)
    at clojure.core$load.doInvoke(core.clj:5865)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5671)
    at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
    at clojure.core$load_lib.doInvoke(core.clj:5710)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:632)
    at clojure.core$load_libs.doInvoke(core.clj:5749)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:632)
    at clojure.core$require.doInvoke(core.clj:5832)
    at clojure.lang.RestFn.invoke(RestFn.java:436)
    at ultra.hardcore$eval7283$loading__5340__auto____7284.invoke(hardcore.clj:1)
    at ultra.hardcore$eval7283.invoke(hardcore.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6782)
    at clojure.lang.Compiler.eval(Compiler.java:6771)
    at clojure.lang.Compiler.load(Compiler.java:7227)
    at clojure.lang.RT.loadResourceScript(RT.java:371)
    at clojure.lang.RT.loadResourceScript(RT.java:362)
    at clojure.lang.RT.load(RT.java:446)
    at clojure.lang.RT.load(RT.java:412)
    at clojure.core$load$fn__5448.invoke(core.clj:5866)
    at clojure.core$load.doInvoke(core.clj:5865)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5671)
    at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
    at clojure.core$load_lib.doInvoke(core.clj:5710)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:632)
    at clojure.core$load_libs.doInvoke(core.clj:5749)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:632)
    at clojure.core$require.doInvoke(core.clj:5832)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at user$eval7279.invoke(form-init9175779932045358263.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6782)
    at clojure.lang.Compiler.eval(Compiler.java:6771)
    at clojure.lang.Compiler.load(Compiler.java:7227)
    at clojure.lang.Compiler.loadFile(Compiler.java:7165)
    at clojure.main$load_script.invoke(main.clj:275)
    at clojure.main$init_opt.invoke(main.clj:280)
    at clojure.main$initialize.invoke(main.clj:308)
    at clojure.main$null_opt.invoke(main.clj:343)
    at clojure.main$main.doInvoke(main.clj:421)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:383)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.main.main(main.java:37)
Caused by: java.io.FileNotFoundException: Could not locate puget/dispatch__init.class or puget/dispatch.clj on classpath.
    at clojure.lang.RT.load(RT.java:449)
    at clojure.lang.RT.load(RT.java:412)
    at clojure.core$load$fn__5448.invoke(core.clj:5866)
    at clojure.core$load.doInvoke(core.clj:5865)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5671)
    at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
    at clojure.core$load_lib.doInvoke(core.clj:5710)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:632)
    at clojure.core$load_libs.doInvoke(core.clj:5749)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:632)
    at clojure.core$require.doInvoke(core.clj:5832)
    at clojure.lang.RestFn.invoke(RestFn.java:457)
    at whidbey.repl$eval8173$loading__5340__auto____8174.invoke(repl.clj:1)
    at whidbey.repl$eval8173.invoke(repl.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6782)
    at clojure.lang.Compiler.eval(Compiler.java:6771)
    at clojure.lang.Compiler.load(Compiler.java:7227)
    ... 76 more
```

Lein version:

```
[rcanepa@Renzos-MacBook-Pro:swagger-service (master)] λ lein -version
Leiningen 2.5.3 on Java 1.8.0_45 Java HotSpot(TM) 64-Bit Server VM
```

Java version:

```
[rcanepa@Renzos-MacBook-Pro:~] λ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

Any thoughts on why I am getting this error?.

Anyway, thanks for the tutorial!

**Comment by yogthos** [comment]
The only thing I can think of is that you might have a plugin in your `.lein/profiles.clj` that's conflicting with something. Duct might've been updated as well since the tutorial, but I suspect it's a plugin. :)

**Comment by rcanepa** [comment]
You are right. That was the problem. 

My .lein/profiles.clj looked like this:

```
{:user {:plugins [[cider/cider-nrepl "0.10.0-SNAPSHOT"]
                  [refactor-nrepl "1.2.0-SNAPSHOT"]
                  [jonase/eastwood "0.2.2"]
                  [venantius/ultra "0.4.0"]]
        :dependencies [[alembic "0.3.2"]
                       [org.clojure/tools.nrepl "0.2.10"]]}}
```

After replacing it, all went well. Thanks!

**Comment by yogthos** [comment]
great, that was easy :)
